# Generated by Django 5.1.3 on 2025-02-06 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='images/photos')),
            ],
            options={
                'verbose_name': 'Afiliación',
                'verbose_name_plural': 'Afiliaciones',
            },
        ),
        migrations.CreateModel(
            name='ElementoPersonaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='images/elements')),
            ],
            options={
                'verbose_name': 'Elemento',
                'verbose_name_plural': 'Elementos',
            },
        ),
        migrations.CreateModel(
            name='Enemigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='images/enemies')),
            ],
            options={
                'verbose_name': 'Enemigo',
                'verbose_name_plural': 'Enemigos',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('bono', models.CharField(max_length=300, verbose_name='Bono')),
                ('imagen', models.ImageField(upload_to='images/equipment')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='images/functions')),
            ],
            options={
                'verbose_name': 'Función',
                'verbose_name_plural': 'Funciones',
            },
        ),
        migrations.CreateModel(
            name='HabilidadArma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Habilidad de arma',
                'verbose_name_plural': 'Habilidades de arma',
            },
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Mapa',
                'verbose_name_plural': 'Mapas',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='images/materials')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='MetodoObtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=50, verbose_name='Método')),
            ],
            options={
                'verbose_name': 'Método de obtención',
                'verbose_name_plural': 'Métodos de obtención',
            },
        ),
        migrations.CreateModel(
            name='Rareza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='images/rarities')),
            ],
            options={
                'verbose_name': 'Rareza',
                'verbose_name_plural': 'Rarezas',
            },
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armas_funcion', to='app_proyecto.funcion')),
                ('habilidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arma_habilidad', to='app_proyecto.habilidadarma')),
                ('rareza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armas_rareza', to='app_proyecto.rareza')),
            ],
            options={
                'verbose_name': 'Arma',
                'verbose_name_plural': 'Armas',
            },
        ),
        migrations.CreateModel(
            name='ImagenArma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='images/weapons')),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_arma', to='app_proyecto.arma')),
            ],
            options={
                'verbose_name': 'Imagen del Arma',
                'verbose_name_plural': 'Imágenes del Arma',
            },
        ),
        migrations.CreateModel(
            name='ImagenMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='images/maps')),
                ('mapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_mapa', to='app_proyecto.mapa')),
            ],
            options={
                'verbose_name': 'Imagen de mapa',
                'verbose_name_plural': 'Imágenes de mapa',
            },
        ),
        migrations.CreateModel(
            name='HabilidadPersonaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='images/skills')),
                ('materiales', models.ManyToManyField(related_name='habilidades_materiales', to='app_proyecto.material')),
            ],
            options={
                'verbose_name': 'Habilidad de personaje',
                'verbose_name_plural': 'Habilidades de personaje',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='obtencion',
            field=models.ManyToManyField(related_name='materiales_obtencion', to='app_proyecto.metodoobtencion'),
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('titulo', models.CharField(blank=True, max_length=50, verbose_name='Título')),
                ('descripcion', models.CharField(blank=True, max_length=300, verbose_name='Descripción')),
                ('afiliacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personajes_afiliacion', to='app_proyecto.afiliacion')),
                ('armas', models.ManyToManyField(blank=True, related_name='personajes_armas', to='app_proyecto.arma')),
                ('elemento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personajes_elemento', to='app_proyecto.elementopersonaje')),
                ('equipo', models.ManyToManyField(blank=True, related_name='personajes_equipo', to='app_proyecto.equipo')),
                ('funcion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personajes_funcion', to='app_proyecto.funcion')),
                ('habilidades', models.ManyToManyField(related_name='personajes_habilidades', to='app_proyecto.habilidadpersonaje')),
                ('sinergias', models.ManyToManyField(blank=True, related_name='personajes_sinergias', to='app_proyecto.personaje')),
                ('rareza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personajes_rareza', to='app_proyecto.rareza')),
            ],
            options={
                'verbose_name': 'Personaje',
                'verbose_name_plural': 'Personajes',
            },
        ),
        migrations.CreateModel(
            name='ImagenPersonaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='images/characters')),
                ('personaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_personaje', to='app_proyecto.personaje')),
            ],
            options={
                'verbose_name': 'Imagen del Personaje',
                'verbose_name_plural': 'Imágenes del Personaje',
            },
        ),
        migrations.CreateModel(
            name='PiezaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='images/equipment_pieces')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas_equipo', to='app_proyecto.equipo')),
            ],
            options={
                'verbose_name': 'Pieza de equipo',
                'verbose_name_plural': 'Piezas de equipo',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='rareza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales_rareza', to='app_proyecto.rareza'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='rareza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_rareza', to='app_proyecto.rareza'),
        ),
    ]
