# Generated by Django 5.1.3 on 2025-06-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_proyecto', '0002_equipo_tipo_piezaequipo_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidadpersonaje',
            name='tipo',
            field=models.CharField(choices=[('ATQ básico', 'ATQ básico'), ('Habilidad básica', 'Habilidad básica'), ('Habilidad definitiva', 'Habilidad definitiva'), ('Talento', 'Talento')], default='Activa', max_length=100, verbose_name='Tipo'),
        ),
    ]
